### ISSUE TITLE
Invisible Captcha

### ISSUE THREAD

**Issue by prathers** [waldhacker/ext-hcaptcha#12]
Feature request:

https://docs.hcaptcha.com/invisible

The captcha method is a growing challenge for users. An invisible feature would be a big improvement.

**Comment by waldhacker1** [comment]
Hi @prathers   
thanks for your contribution!
Please reopen your issue in the [new repository location](https://github.com/dreistromland/typo3-ext-hcaptcha) if it is still relevant.

Thank you very much!
