### ISSUE TITLE
hCapture button missing on forms in typo3 11.5.16

### ISSUE THREAD

**Issue by ProWebs** [waldhacker/ext-hcaptcha#15]
I installed you extension hcapture 2.0.3 on our typo3 11.5.16 project but the button "hCapture" will be not shown on forms.
Clearing cache also won't fix the issues.

Constants:
`# hCaptcha
plugin.tx_hcaptcha {
    settings {
        publicKey = Site Key
        privateKey = Secret Key
    }
}`

**Comment by waldhacker1** [comment]
Did you add the form element to your form (https://docs.typo3.org/p/waldhacker/hcaptcha/2.0/en-us/Editor/Index.html#for-editors)?

Or do you mean that you don't see the form element in the form editor?

**Comment by issibi** [comment]
Here the same, installed extension via  Extensionmanager, set the keys in TS but the Button does not show up in the from editor. Cleared cache in install tool.
 TYPO3 11.5.10

**Comment by SoundstormVFX** [comment]
I have the same problem, no form element in the form editor. Flushing TYPO3 and PHP Cache does not help.
EXT Vers. 2.04, TYPO3 11.5.7

**Comment by waldhacker1** [comment]
@SoundstormVFX Did you also install the extension from the TER / via  Extensionmanager?

**Comment by waldhacker1** [comment]
This has now been fixed with version 2.1.1.
At the moment it is not possible to release into TER, but as soon as this is possible again, the version 2.1.1 can be used in non-composer TYPO3 installations too.
