### ISSUE TITLE
Add powermail support

### ISSUE THREAD

**Issue by susannemoog** [waldhacker/ext-hcaptcha#2]

**Comment by NoHara42** [comment]
Bumping this because I am also interested in powermail support, has this been implemented/discussed?
Thanks.

**Comment by waldhacker1** [comment]
Hi @NoHara42   
thanks for your contribution!
Please reopen your issue in the [new repository location](https://github.com/dreistromland/typo3-ext-hcaptcha) if it is still relevant.

Thank you very much!
