### ISSUE TITLE
Allow to translate the extension on Crowdin

### ISSUE THREAD

**Issue by dogawaf** [waldhacker/ext-hcaptcha#20]
Hello

It would be perfect if we can add translation to this extension through Crowdin.
The onboarding process is described here: https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/Localization/TranslationServer/Crowdin/ExtensionIntegration.html

Cheers

**Comment by waldhacker1** [comment]
Hi @dogawaf   
thanks for your contribution!
Please reopen your issue in the [new repository location](https://github.com/dreistromland/typo3-ext-hcaptcha) if it is still relevant.

Thank you very much!
