### ISSUE TITLE
TYPO3 12 LTS Compatibility

### ISSUE THREAD

**Issue by g-nebel** [waldhacker/ext-hcaptcha#21]
The Requiremnet of the Extension is still TYPO3 - 12.1.99.
Apparently the extension is also compatible with the TYPO3 12 LTS (12.4.x)

**Comment by g-nebel** [comment]
Patch for TYPO3 12 LTS Compatibility and PHP 8.2 Compatibility 
[typo3lts12compatibility.patch](https://github.com/waldhacker/ext-hcaptcha/files/12308284/typo3lts12compatibility.patch)

**Comment by waldhacker1** [comment]
Thanks for your report.
Version 2.1.3 is now compatible with TYPO3 v12 LTS.
