### ISSUE TITLE
Minor incompatibility with helhum/typo3-secure-web

### ISSUE THREAD

**Issue by xperseguers** [waldhacker/ext-hcaptcha#3]
The extension icon is present at root as `ext_icon.svg`. In order to be compatible (and thus visible in Backend) when using package `helhum/typo3-secure-web`, it should be moved to `Resources/Public/Icons/Extension.svg`.

Never checked with SVG but it works fine for PNG even when not using this security package (thus easy to test that icon is still there after moving and renaming it).

Thanks.

**Comment by waldhacker1** [comment]
Fixed in 2.0.1
