### ISSUE TITLE
[BUG] Viewing the form in the backend is not working

### ISSUE THREAD

**Issue by PhilippKuhlmay** [waldhacker/ext-hcaptcha#8]
I cannot view my form inside the backend using the preview mode.
I get an error when trying to view it.

- open a form in the form module
- clock on the "preview" button

<img width="997" alt="Bildschirmfoto 2022-01-21 um 13 50" src="https://user-images.githubusercontent.com/57705869/150530114-a56a2e2f-7083-4e60-afc4-a25e894d5e08.png">

I have both private and public key inside my typoscript

**Comment by waldhacker1** [comment]
Thx for reporting this. Should be fixed in version 2.0.3

**Comment by PhilippKuhlmay** [comment]
> Thx for reporting this. Should be fixed in version 2.0.3

Yes it is fixed for me. Thanks.
